query getUsers($skipUserPosts: Boolean! = false) {
  users:getUsers {
    ...user
  }
}

query getUser($getEmail: String!, $skipUserPosts: Boolean! = false) {
  users:getUser(email: $getEmail) {
    ...user
  }
}

query getPosts($skipUserPosts: Boolean! = true) {
  # post: getPost(id: $getId) {
  #   ...user
  # }
  posts:getPosts {
    ...post
  }
}

mutation createPost($post: PostCreateInput!, $skipUserPosts: Boolean! = false) {
  post: createPost(post: $post) {
    ...post
  }
}

mutation createUser($user: UserCreateInput!, $skipUserPosts: Boolean! = false) {
  user: createUser(data: $user) {
    ...user
  }
}

mutation updateUser($upId: Int!, $phone: String, $skipUserPosts: Boolean! = false) {
  user: updateUser(id: $upId, phone: $phone) {
    ...user
  }
}

mutation deleteUser($delEmail: String!, $skipUserPosts: Boolean! = false) {
  user: deleteUser(email: $delEmail) {
    ...user
  }
}

fragment posts on Post {
  id, title, content, published
}

fragment user on User {
  id, name, email, phone, posts {
    ... posts @skip(if: $skipUserPosts)
  }
}

fragment post on Post {
  id, title, content, published, author { ...user }
}


####variables
{
  "getEmail": "t3@yopmail",
  "delEmail": "t3@yopmail",
  "upId": 1,
  "user": {
    "phone": "958787785",
  	"name": "Test3",
  	"email": "t3@yopmail.com" 
  },
  "post": {
    "title": "Happiness",
    "content": "What is happiness? It's a mental state...",
    "author": {
      "connect": {
        "id": 1
      }
    }
  }
}


###headers
{
  "app_key":"absaja"
}